FROM hirokimatsumoto/alpine-openjdk-11
EXPOSE 9090

ARG jar_file_name=counterclinic-walkin.jar
ADD target/counterclinic-0.0.1-SNAPSHOT.jar ${jar_file_name}
ENTRYPOINT ["java", "-jar", ${jar_file_name}]
